disabled_rules: # rule identifiers to exclude from running
  - multiple_closures_with_trailing_closure
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - FlowerForever/AppDelegate.swift
