# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'learnRxSwiftWithStyle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for learnRxSwiftWithStyle
   pod 'RxSwift', '~> 4.5' 
   pod 'RxCocoa', '~> 4.5' 
   pod 'RxDataSources', '~> 3.1.0'
target 'learnRxSwiftWithStyleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
