# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlowerForeverMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlowerForeverMVVM
    pod 'Alamofire', '~> 4.0'
    pod 'SwiftLint'
    pod 'RealmSwift'
    pod 'RxSwift', '~> 4.5'
    pod 'RxCocoa', '~> 4.5' 
    pod 'Action'

target 'FlowerForeverMVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
